### ISSUE TITLE
Could not create widget Exitintent.widget.Exitintent error in v7.16.0

### ISSUE THREAD

**Issue by ateale** [cdcharlebois/ExitIntent#3]
Hello,

I get the following error trying to use the widget in v7.16.0 of the modeller when the new/edit page loads:

"Could not create widget Exitintent.widget.Exitintent"

![Exitintent2](https://user-images.githubusercontent.com/46445328/58861453-4f060b00-86a6-11e9-939e-25aa9a92a1b9.PNG)

Regards
Adrian

**Comment by tieniber** [comment]
Fixed in the release 1.1.0 for Mx7 and 8
